name: VIPSlots
main: iJoshuaHD\VIPSlots
version: 0.0.5
api: [3.0.09]
load: STARTUP
author: iJoshuaHD
description: Enable VIP players to join full servers.
website: https://github.com/ijoshuahd/VIPSlots
commands:
 vips:
  description: "Set Permissions"
  permission: vips.command.vips
permissions:
  vips.command.vips:
    default: op
    description: "/vips <add/remove/list>"
